interlinks:
  fast: true

quartodoc:
  dir: reference
  package: gen_tso
  out_index: index.qmd
  sections:
  - title: API Reference
    options:
      dynamic: true
    contents:
    - name: pandeia_io.make_scene

