quartodoc:
  style: pkgdown
  dir: api
  out_index: index.qmd
  package: gen_tso
  dynamic: true
  #renderer:
  #  style: _renderer.py
  #  show_signature_annotations: false

  sections:
  - title: Pandeia
    desc: Pandeia interface functions
    contents:
    - pandeia_io.make_scene
    - pandeia_io.PandeiaCalculation
    - pandeia_io.exposure_time

  - title: catalogs
    desc: Exoplanet catalogs
    package: gen_tso.catalogs
    contents:
    - Catalog
    - load_trexolist_table
