project:
  type: website
  output-dir: _site

execute:
  freeze: auto

# tell quarto to read the generated sidebar
#metadata-files:
#  - _sidebar.yml

format:
  html:
    theme:
      light: cosmo
    #css: styles.css
    toc: true
    toc-location: left

website:
  page-navigation: true
  title: "Gen TSO"
  description: "A graphical ETC interface for time-series observations"
  repo-url: https://github.com/pcubillos/gen_tso
  back-to-top-navigation: true

  page-footer:
    left: "&copy; CC-By Patricio Cubillos, 2024"
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/gen_tso_logo.png"
    #subtitle: "Version 0.0.0"
    pinned: true
    align: center
    style: "docked"
    background: "#F9F9F9"

    contents:
    - text: "Version 0.1.0"

  # Add links to the top
  navbar:
    background: "#F2F2F2"
    pinned: true
    left:
    - file: install.qmd
      text: Installation
    - file: get_started.qmd
      text: Get started
    - text: API
      href: api

    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/pcubillos/gen_tso
          - text: Report a Bug
            href:  https://github.com/pcubillos/gen_tso/issues


#quartodoc:
#  style: pkgdown
#  dir: api
#  out_index: index.qmd
#  package: gen_tso
#  dynamic: true
#  #renderer:
#  #  style: _renderer.py
#  #  show_signature_annotations: false
#
#  sections:
#  - title: Pandeia
#    desc: Pandeia interface functions
#    contents:
#    - pandeia_io.make_scene
#    - pandeia_io.PandeiaCalculation
#    - pandeia_io.exposure_time
#
#  - title: catalogs
#    desc: Exoplanet catalogs
#    package: gen_tso.catalogs
#    contents:
#    - Catalog
#    - load_trexolist_table
