---
title: Getting started
page-navigation: true
---

With `Gen TSO` you can produce JWST simulated spectra in as few as four simple steps.

## 1 Select target

A drop down menu lets you search/type for confirmed planets and TESS candidates
(data provided by the NASA Exoplanet Archive).  Once a target is selected:

- [Editable fileds](select_target.qmd) are automatically filled with the system properties
- A link provides the target's name aliases full system properties
- A link leads you to the NASA Exoplanet Archive
- A link displays the exisiting JWST programs on the host star

---

{{< video images/select_target.webm width='800'>}}

---

## 2 Set instrument and mode

The top menu lets you select the JWST instrument and mode:

- All TSO spectroscopic and acquisition modes are available
- The detector setup panel gets automatically updated for the current instrument
- The right interactive viewer shows the available filter throughputs of the instrument

---

{{< video images/select_instrument.webm width='800'>}}

---

## 3 Set transit/eclipse model

The transit or eclipse depth spectrum encodes the core of a science case,
so this is the one bit of information that a user has to provide.
In the `Gen TSO` application users can:

- Search and [upload transit/eclipse depth spectra](select_planet_model.qmd#uploading-model-files)
- [Pre-load spectra](select_planet_model.qmd#pre-loading-models-at-launch) when launching the application
- Use blackbody or flat-transmission spectra for a quick S/N assessment
- Interactively view and compare spectra in the viewer panel

---

{{< video images/select_transit_depth.webm width='800'>}}

---


## 4 Run Pandeia

Now you are ready to simulate a TSO with JWST.  `Gen TSO` provides many
features to facilitate this step as well. Before a run:

- the text display shows [real-time exposure and saturation](run_pandeia.qmd) values in real time
- The number of integrations can [automatically match the observation duration](run_pandeia.qmd#exposure-times)
- [Saturation times](run_pandeia.qmd#saturation) inform on the optimal number of groups for a target/instrument combination

Once a Pandeia simulation has finished:

- The TSO tab shows [interactive displays](run_pandeia.qmd#figures) of the transit/eclipse depth, S/N, and more
- The *Results* panel shows a [text summary](run_pandeia.qmd#text-outputs) of the simulation, as seen in the official ETC
- The warnings tab alerts users of potential risks
- Finally, [TSO runs can be saved](run_pandeia.qmd#collecting-outputs) into Python pickle files for later use

---

{{< video images/run_pandeia.webm width='800'>}}

---


## Bonus: Target Acquisition

Here's one my favorite features.  While `Gen TSO` offers acquisition on a
science target, sometimes the target is just too bright.  For such cases you can:

- Search for Gaia stellar sources around the science target
- Use the `ESASky` viewer to guide and select a nearby target
- Run the acquisition on the nearby target

---

{{< video images/target_acquisition.webm width='800'>}}



