---
title: "Gen TSO Documentation"
author: "Patricio Cubillos"
date: today
output: html_document
page-navigation: true
---

---

### Gen TSO

<div style="margin-top: -0.6em; font-weight: bold; font-size: 1.3rem;">
A general TSO simulator for exoplanets with JWST
</div>

`Gen TSO` is a graphical interface to simulate JWST time-series
observations (TSO) of exoplanets.  Gen TSO connects together:

- The [JWST's Pandeia ETC engine](https://outerspace.stsci.edu/display/PEN/Pandeia+Engine+News)
- The [NASA Exoplanet Archive](https://exoplanetarchive.ipac.caltech.edu/)
- The [trexolists database](https://www.stsci.edu/~nnikolov/TrExoLiSTS/JWST/trexolists.html) of JWST TSO programs
- The [Gaia catalog](https://gea.esac.esa.int/archive/) of stellar sources

Which combined, allow `Gen TSO` to offers an interactive interface to easily
visualize, assess, and compare the JWST characterization capabilities
for known exoplanets.

`Gen TSO` provides:

- Instant access to system parameters of known exoplanet targets
- Instant access to previous JWST programs of targets
- Interactive visualization of target's field of view with [ESASky](https://sky.esa.int/esasky/)
- Perform transit and eclipse S/N simulations for **all JWST spectroscopic and photometric TSO modes**
- Perform target-acquisition simulations on science or nearby targets
- Interactive visualization of transit, eclipse, and stellar SEDs spectra, observing modes, and simulated TSO spectra
- A **GUI-to-notebook button** to instantly translate the current GUI state to a Python script

---

### Install

`Gen TSO` is a Python3.9+ package available via the PyPI repository:

```bash
pip install gen_tso
```

Then, you can launch the `Gen TSO` application with this prompt command:
```bash
tso
```

---

### JWST observing modes

These are the available TSO modes for each instrument:


```{=html}

<table style="background-color: #f5f5f5; border-collapse: collapse; width: 100%;">

  <colgroup>
    <col style="width: 30%;">
    <col style="width: 30%;">
    <col style="width: 40%;">
  </colgroup>

  <thead style="background-color: #e0e0e0;">
    <tr>
      <th><span data-qmd="Instrument"></span></th>
      <th><span data-qmd="Spectroscopy modes"></span></th>
      <th><span data-qmd="Wavelength range (&mu;m)"></span></th>
    </tr>
  </thead>

  <tbody>
    <tr>
        <td rowspan="2"><span data-qmd="__miri__"></span></td>
        <td>lrsslitless</td> <td>5.0 &#8211; 12</td>
    </tr>
    <tr>
        <td>mrs_ts</td> <td>5.0 &#8211; 28</td>
    </tr>
    <tr>
        <td rowspan="2"><span data-qmd="__nircam__"></span></td>
        <td>lw_tsgrism</td> <td>2.4 &#8211; 5.0</td>
    </tr>
    <tr>
        <td>sw_tsgrism</td> <td>0.6 &#8211; 2.2</td>
    </tr>
    <tr>
        <td><span data-qmd="__niriss__"></span></td> <td>soss</td> <td>0.6 &#8211; 2.8</td>
    </tr>

    <tr>
        <td><span data-qmd="__nirspec__"></span></td> <td>bots</td> <td>0.6 &#8211; 5.2</td>
    </tr>
  </tbody>
</table>
```

```{=html}
<table style="background-color: #f5f5f5; border-collapse: collapse;">

  <colgroup>
    <col style="width: 30%;">
    <col style="width: 30%;">
    <col style="width: 40%;">
  </colgroup>

  <thead style="background-color: #e0e0e0;">
    <tr>
      <th><span data-qmd="Instrument"></span></th>
      <th><span data-qmd="Photometry modes"></span></th>
      <th><span data-qmd="Wavelength range (&mu;m)"></span></th>
    </tr>
  </thead>

  <tbody style="background-color: #fafafa;">
    <tr>
        <td><span data-qmd="__miri__"></span></td> <td>imaging_ts</td> <td>5.0 &#8211; 30</td>
    </tr>
    <tr>
        <td rowspan="2"><span data-qmd="__nircam__"></span></td>
        <td>lw_ts</td> <td>2.4 &#8211; 5.2</td>
    </tr>
    <tr>
        <td>sw_ts</td> <td>0.6 &#8211; 2.4</td>
    </tr>
  </tbody>
</table>
```

```{=html}
<table style="background-color: #f5f5f5; border-collapse: collapse;">

  <colgroup>
    <col style="width: 30%;">
    <col style="width: 70%;">
  </colgroup>

  <thead style="background-color: #e0e0e0;">
    <tr>
      <th><span data-qmd="Instrument"></span></th>
      <th><span data-qmd="Acquisition modes"></span></th>
    </tr>
  </thead>

  <tbody style="background-color: #fafafa;">
    <tr>
        <td><span data-qmd="__miri__"></span></td> <td>target_acq</td>
    </tr>
    <tr>
        <td><span data-qmd="__nircam__"></span></td><td>target_acq</td>
    </tr>
    <tr>
        <td><span data-qmd="__niriss__"></span></td> <td>target_acq</td>
    </tr>

    <tr>
        <td><span data-qmd="__nirspec__"></span></td> <td>target_acq</td>
    </tr>
  </tbody>
</table>
```


---

### Citing

Please cite this paper if you found ``Gen TSO`` useful for your research: <br>
  [Cubillos (2024): Gen TSO: A General JWST Simulator for Exoplanet Times-series Observations](https://ui.adsabs.harvard.edu/abs/2024PASP..136l4501C)


BibTeX reference:

```bibtex
@ARTICLE{Cubillos2024paspGenTSO,
       author = {{Cubillos}, Patricio E.},
        title = "{Gen TSO: A General JWST Simulator for Exoplanet Times-series Observations}",
      journal = {\pasp},
     keywords = {Exoplanets, Time series analysis, Astronomy databases, 498, 1916, 83, Astrophysics - Earth and Planetary Astrophysics, Astrophysics - Instrumentation and Methods for Astrophysics},
         year = 2024,
        month = dec,
       volume = {136},
       number = {12},
          eid = {124501},
        pages = {124501},
          doi = {10.1088/1538-3873/ad8fd4},
archivePrefix = {arXiv},
       eprint = {2410.04856},
 primaryClass = {astro-ph.EP},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2024PASP..136l4501C},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

We welcome your feedback or inquiries, please raise issues on the [Github repository](https://github.com/pcubillos/gen_tso/issues) or refer them to: <br>
Patricio Cubillos (`patricio.cubillos[at]oeaw.ac.at`)

---

Find more information in the links below:

<div style="display: flex; justify-content: center; gap: 2rem; margin: 2rem 0; text-align: center; font-weight: bold; font-size: 1.1rem;">

  <div style="border: 2px solid #cccccc; border-radius: 12px; padding: 1rem; text-align: center; width: 135px;">
  <a href="install.html" style="text-decoration: none; color: #777777;">
    <i class="fa-solid fa-download" style="font-size: 3.5rem; color: #444444;"></i><br>
    <strong>Install</strong>
  </a>
  </div>

  <div style="border: 2px solid #cccccc; border-radius: 12px; padding: 1rem; text-align: center; width: 135px;">
  <a href="get_started.html" style="text-decoration: none; color: #777777;">
      <i class="fa-solid fa-rocket" style="font-size: 3.5rem; color: #444444;"></i><br>
      Get Started
  </a>
  </div>

  <div style="border: 2px solid #cccccc; border-radius: 12px; padding: 1rem; text-align: center; width: 135px;">
  <a href="tutorials.html" style="text-decoration: none; color: #777777;">
      <i class="fa-solid fa-book" style="font-size: 3.5rem; color: #444444;"></i><br>
      Tutorials
  </a>
  </div>

  <div style="border: 2px solid #cccccc; border-radius: 12px; padding: 1rem; text-align: center; width: 135px;">
  <a href="api.html" style="text-decoration: none; color: #777777;">
      <i class="fa-solid fa-code" style="font-size: 3.5rem; color: #444444;"></i><br>
      API
  </a>
  </div>

</div>

---

