on:
  push:
    branches:
      - master
      - docs
  workflow_dispatch:


name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write
    id-token: write


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  render-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install quartodoc

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Compile docstrings with quartodoc
        shell: bash
        run: |
          pushd docs; make doc; popd

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: 'docs'

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload quarto render output directory
          path: 'docs/_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # add software dependencies here and any libraries

      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

